// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen(arg1) {
  return window['go']['crud']['CrudToken']['CaptureScreen'](arg1);
}

export function CaptureScreenQRCode(arg1, arg2) {
  return window['go']['crud']['CrudToken']['CaptureScreenQRCode'](arg1, arg2);
}

export function TokenCreate(arg1) {
  return window['go']['crud']['CrudToken']['TokenCreate'](arg1);
}

export function TokenDelete(arg1) {
  return window['go']['crud']['CrudToken']['TokenDelete'](arg1);
}

export function TokenInfo(arg1, arg2) {
  return window['go']['crud']['CrudToken']['TokenInfo'](arg1, arg2);
}

export function TokenList(arg1) {
  return window['go']['crud']['CrudToken']['TokenList'](arg1);
}

export function TokenTimeCode(arg1) {
  return window['go']['crud']['CrudToken']['TokenTimeCode'](arg1);
}

export function TokenUpdate(arg1, arg2, arg3) {
  return window['go']['crud']['CrudToken']['TokenUpdate'](arg1, arg2, arg3);
}
