// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen(arg1) {
  return window['go']['crud']['CrudToken']['CaptureScreen'](arg1);
}

export function CaptureScreenQRCode(arg1, arg2) {
  return window['go']['crud']['CrudToken']['CaptureScreenQRCode'](arg1, arg2);
}

export function TokenCreate() {
  return window['go']['crud']['CrudToken']['TokenCreate']();
}

export function TokenDelete() {
  return window['go']['crud']['CrudToken']['TokenDelete']();
}

export function TokenList(arg1) {
  return window['go']['crud']['CrudToken']['TokenList'](arg1);
}

export function TokenUpdate() {
  return window['go']['crud']['CrudToken']['TokenUpdate']();
}
