// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen(arg1:number):Promise<string>;

export function CaptureScreenQRCode(arg1:Array<number>,arg2:Array<number>):Promise<string>;

export function TokenCreate(arg1:string):Promise<string>;

export function TokenDelete(arg1:string):Promise<string>;

export function TokenInfo(arg1:string,arg2:string):Promise<string>;

export function TokenList(arg1:string):Promise<string>;

export function TokenTimeCode(arg1:string):Promise<string>;

export function TokenUpdate(arg1:string,arg2:string,arg3:string):Promise<string>;
