// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen() {
  return window['go']['main']['App']['CaptureScreen']();
}

export function CaptureScreenQRCode(arg1, arg2) {
  return window['go']['main']['App']['CaptureScreenQRCode'](arg1, arg2);
}
