// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToken'](arg1, arg2, arg3);
}

export function GetDiretory() {
  return window['go']['main']['App']['GetDiretory']();
}

export function GetFile(arg1) {
  return window['go']['main']['App']['GetFile'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ImportToken(arg1, arg2) {
  return window['go']['main']['App']['ImportToken'](arg1, arg2);
}

export function ListAlgoritm() {
  return window['go']['main']['App']['ListAlgoritm']();
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}
