// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportToken(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDiretory():Promise<string>;

export function GetFile(arg1:string):Promise<string>;

export function GetSettings():Promise<string>;

export function ListAlgoritm():Promise<string>;

export function SaveFileDialog(arg1:string):Promise<string>;

export function SetSettings(arg1:string):Promise<string>;
