// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen():Promise<string>;

export function CaptureScreenQRCode(arg1:Array<number>,arg2:Array<number>):Promise<string>;
